# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sdm632-modules/motorola/include \
		-I$(KERNEL_SRC)/../sdm632-modules/motorola/drivers/power/bq2597x_mmi

obj-m += bq2597x_mmi.o
