# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sdm632-modules/motorola/include \


goodix_fod_mmi-y += gf_spi.o netlink.o platform.o

obj-m += goodix_fod_mmi.o

